name: Quantum Pulse Scheduled Run

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  run_quantum_pulse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Quantum Pulse engine
        env:
          FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
        run: |
          python quantum_signal_engine.py
